
  create table "public"."backlogs" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "updated_at" time with time zone,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid
      );


alter table "public"."backlogs" enable row level security;

CREATE UNIQUE INDEX backlog_pkey ON public.backlogs USING btree (id);

alter table "public"."backlogs" add constraint "backlog_pkey" PRIMARY KEY using index "backlog_pkey";

alter table "public"."backlogs" add constraint "backlogs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."backlogs" validate constraint "backlogs_user_id_fkey";

grant delete on table "public"."backlogs" to "anon";

grant insert on table "public"."backlogs" to "anon";

grant references on table "public"."backlogs" to "anon";

grant select on table "public"."backlogs" to "anon";

grant trigger on table "public"."backlogs" to "anon";

grant truncate on table "public"."backlogs" to "anon";

grant update on table "public"."backlogs" to "anon";

grant delete on table "public"."backlogs" to "authenticated";

grant insert on table "public"."backlogs" to "authenticated";

grant references on table "public"."backlogs" to "authenticated";

grant select on table "public"."backlogs" to "authenticated";

grant trigger on table "public"."backlogs" to "authenticated";

grant truncate on table "public"."backlogs" to "authenticated";

grant update on table "public"."backlogs" to "authenticated";

grant delete on table "public"."backlogs" to "postgres";

grant insert on table "public"."backlogs" to "postgres";

grant references on table "public"."backlogs" to "postgres";

grant select on table "public"."backlogs" to "postgres";

grant trigger on table "public"."backlogs" to "postgres";

grant truncate on table "public"."backlogs" to "postgres";

grant update on table "public"."backlogs" to "postgres";

grant delete on table "public"."backlogs" to "service_role";

grant insert on table "public"."backlogs" to "service_role";

grant references on table "public"."backlogs" to "service_role";

grant select on table "public"."backlogs" to "service_role";

grant trigger on table "public"."backlogs" to "service_role";

grant truncate on table "public"."backlogs" to "service_role";

grant update on table "public"."backlogs" to "service_role";


  create policy "Enable delete for users based on user_id"
  on "public"."backlogs"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."backlogs"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."backlogs"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



