create table public.games (
  id bigint generated by default as identity not null,
  name character varying not null,
  slug character varying null,
  background_image character varying null,
  backlog_id bigint null,
  raw_json json null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  user_id uuid null,
  rawg_id character varying null,
  constraint games_pkey primary key (id),
  constraint games_backlog_id_fkey foreign KEY (backlog_id) references backlogs (id) on update CASCADE on delete CASCADE,
  constraint games_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;